package au.rms.nsw.gov.au.model.hibernate;
// Generated 14/10/2016 12:10:24 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CritCmplxityMsrId generated by hbm2java
 */
@Embeddable
public class CritCmplxityMsrId implements java.io.Serializable {

	private String complexityCode;
	private BigDecimal criteriaId;

	public CritCmplxityMsrId() {
	}

	public CritCmplxityMsrId(String complexityCode, BigDecimal criteriaId) {
		this.complexityCode = complexityCode;
		this.criteriaId = criteriaId;
	}

	@Column(name = "COMPLEXITY_CODE", nullable = false, length = 5)
	public String getComplexityCode() {
		return this.complexityCode;
	}

	public void setComplexityCode(String complexityCode) {
		this.complexityCode = complexityCode;
	}

	@Column(name = "CRITERIA_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCriteriaId() {
		return this.criteriaId;
	}

	public void setCriteriaId(BigDecimal criteriaId) {
		this.criteriaId = criteriaId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CritCmplxityMsrId))
			return false;
		CritCmplxityMsrId castOther = (CritCmplxityMsrId) other;

		return ((this.getComplexityCode() == castOther.getComplexityCode())
				|| (this.getComplexityCode() != null && castOther.getComplexityCode() != null
						&& this.getComplexityCode().equals(castOther.getComplexityCode())))
				&& ((this.getCriteriaId() == castOther.getCriteriaId())
						|| (this.getCriteriaId() != null && castOther.getCriteriaId() != null
								&& this.getCriteriaId().equals(castOther.getCriteriaId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getComplexityCode() == null ? 0 : this.getComplexityCode().hashCode());
		result = 37 * result + (getCriteriaId() == null ? 0 : this.getCriteriaId().hashCode());
		return result;
	}

}
