package au.rms.nsw.gov.au.model.hibernate;
// Generated 14/10/2016 12:10:24 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CritCmplxityMsr generated by hbm2java
 */
@Entity
@Table(name = "CRIT_CMPLXITY_MSR", schema = "ESTADM")
public class CritCmplxityMsr implements java.io.Serializable {

	private CritCmplxityMsrId id;
	private RefComplexity refComplexityByCmplxityDefn;
	private RefComplexity refComplexityByComplexityCode;
	private RefCriteria refCriteria;
	private BigDecimal minimum;
	private BigDecimal maximum;

	public CritCmplxityMsr() {
	}

	public CritCmplxityMsr(CritCmplxityMsrId id, RefComplexity refComplexityByComplexityCode, RefCriteria refCriteria) {
		this.id = id;
		this.refComplexityByComplexityCode = refComplexityByComplexityCode;
		this.refCriteria = refCriteria;
	}

	public CritCmplxityMsr(CritCmplxityMsrId id, RefComplexity refComplexityByCmplxityDefn,
			RefComplexity refComplexityByComplexityCode, RefCriteria refCriteria, BigDecimal minimum,
			BigDecimal maximum) {
		this.id = id;
		this.refComplexityByCmplxityDefn = refComplexityByCmplxityDefn;
		this.refComplexityByComplexityCode = refComplexityByComplexityCode;
		this.refCriteria = refCriteria;
		this.minimum = minimum;
		this.maximum = maximum;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "complexityCode", column = @Column(name = "COMPLEXITY_CODE", nullable = false, length = 5)),
			@AttributeOverride(name = "criteriaId", column = @Column(name = "CRITERIA_ID", nullable = false, precision = 22, scale = 0)) })
	public CritCmplxityMsrId getId() {
		return this.id;
	}

	public void setId(CritCmplxityMsrId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CMPLXITY_DEFN")
	public RefComplexity getRefComplexityByCmplxityDefn() {
		return this.refComplexityByCmplxityDefn;
	}

	public void setRefComplexityByCmplxityDefn(RefComplexity refComplexityByCmplxityDefn) {
		this.refComplexityByCmplxityDefn = refComplexityByCmplxityDefn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPLEXITY_CODE", nullable = false, insertable = false, updatable = false)
	public RefComplexity getRefComplexityByComplexityCode() {
		return this.refComplexityByComplexityCode;
	}

	public void setRefComplexityByComplexityCode(RefComplexity refComplexityByComplexityCode) {
		this.refComplexityByComplexityCode = refComplexityByComplexityCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRITERIA_ID", nullable = false, insertable = false, updatable = false)
	public RefCriteria getRefCriteria() {
		return this.refCriteria;
	}

	public void setRefCriteria(RefCriteria refCriteria) {
		this.refCriteria = refCriteria;
	}

	@Column(name = "MINIMUM", precision = 22, scale = 0)
	public BigDecimal getMinimum() {
		return this.minimum;
	}

	public void setMinimum(BigDecimal minimum) {
		this.minimum = minimum;
	}

	@Column(name = "MAXIMUM", precision = 22, scale = 0)
	public BigDecimal getMaximum() {
		return this.maximum;
	}

	public void setMaximum(BigDecimal maximum) {
		this.maximum = maximum;
	}

}
