package au.rms.nsw.gov.au.model.hibernate;
// Generated 14/10/2016 12:10:24 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OperationComplexityId generated by hbm2java
 */
@Embeddable
public class OperationComplexityId implements java.io.Serializable {

	private BigDecimal prjSrvcMappingId;
	private BigDecimal operationId;
	private String complexityCode;
	private BigDecimal serviceId;

	public OperationComplexityId() {
	}

	public OperationComplexityId(BigDecimal prjSrvcMappingId, BigDecimal operationId, BigDecimal serviceId) {
		this.prjSrvcMappingId = prjSrvcMappingId;
		this.operationId = operationId;
		this.serviceId = serviceId;
	}

	public OperationComplexityId(BigDecimal prjSrvcMappingId, BigDecimal operationId, String complexityCode,
			BigDecimal serviceId) {
		this.prjSrvcMappingId = prjSrvcMappingId;
		this.operationId = operationId;
		this.complexityCode = complexityCode;
		this.serviceId = serviceId;
	}

	@Column(name = "PRJ_SRVC_MAPPING_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getPrjSrvcMappingId() {
		return this.prjSrvcMappingId;
	}

	public void setPrjSrvcMappingId(BigDecimal prjSrvcMappingId) {
		this.prjSrvcMappingId = prjSrvcMappingId;
	}

	@Column(name = "OPERATION_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getOperationId() {
		return this.operationId;
	}

	public void setOperationId(BigDecimal operationId) {
		this.operationId = operationId;
	}

	@Column(name = "COMPLEXITY_CODE", length = 5)
	public String getComplexityCode() {
		return this.complexityCode;
	}

	public void setComplexityCode(String complexityCode) {
		this.complexityCode = complexityCode;
	}

	@Column(name = "SERVICE_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(BigDecimal serviceId) {
		this.serviceId = serviceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OperationComplexityId))
			return false;
		OperationComplexityId castOther = (OperationComplexityId) other;

		return ((this.getPrjSrvcMappingId() == castOther.getPrjSrvcMappingId())
				|| (this.getPrjSrvcMappingId() != null && castOther.getPrjSrvcMappingId() != null
						&& this.getPrjSrvcMappingId().equals(castOther.getPrjSrvcMappingId())))
				&& ((this.getOperationId() == castOther.getOperationId())
						|| (this.getOperationId() != null && castOther.getOperationId() != null
								&& this.getOperationId().equals(castOther.getOperationId())))
				&& ((this.getComplexityCode() == castOther.getComplexityCode())
						|| (this.getComplexityCode() != null && castOther.getComplexityCode() != null
								&& this.getComplexityCode().equals(castOther.getComplexityCode())))
				&& ((this.getServiceId() == castOther.getServiceId()) || (this.getServiceId() != null
						&& castOther.getServiceId() != null && this.getServiceId().equals(castOther.getServiceId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPrjSrvcMappingId() == null ? 0 : this.getPrjSrvcMappingId().hashCode());
		result = 37 * result + (getOperationId() == null ? 0 : this.getOperationId().hashCode());
		result = 37 * result + (getComplexityCode() == null ? 0 : this.getComplexityCode().hashCode());
		result = 37 * result + (getServiceId() == null ? 0 : this.getServiceId().hashCode());
		return result;
	}

}
