package au.rms.nsw.gov.au.model.hibernate;
// Generated 14/10/2016 12:10:24 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrjOpnCritMapping generated by hbm2java
 */
@Entity
@Table(name = "PRJ_OPN_CRIT_MAPPING", schema = "ESTADM")
public class PrjOpnCritMapping implements java.io.Serializable {

	private PrjOpnCritMappingId id;
	private ProjectServiceMapping projectServiceMapping;
	private ServiceOperation serviceOperation;
	private RefCriteriaCustomDefn refCriteriaCustomDefn;
	private BigDecimal criteriaValue;

	public PrjOpnCritMapping() {
	}

	public PrjOpnCritMapping(PrjOpnCritMappingId id, ProjectServiceMapping projectServiceMapping,
			ServiceOperation serviceOperation, RefCriteriaCustomDefn refCriteriaCustomDefn) {
		this.id = id;
		this.projectServiceMapping = projectServiceMapping;
		this.serviceOperation = serviceOperation;
		this.refCriteriaCustomDefn = refCriteriaCustomDefn;
	}

	public PrjOpnCritMapping(PrjOpnCritMappingId id, ProjectServiceMapping projectServiceMapping,
			ServiceOperation serviceOperation, RefCriteriaCustomDefn refCriteriaCustomDefn, BigDecimal criteriaValue) {
		this.id = id;
		this.projectServiceMapping = projectServiceMapping;
		this.serviceOperation = serviceOperation;
		this.refCriteriaCustomDefn = refCriteriaCustomDefn;
		this.criteriaValue = criteriaValue;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "operationId", column = @Column(name = "OPERATION_ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "prjSrvcMappingId", column = @Column(name = "PRJ_SRVC_MAPPING_ID", nullable = false, precision = 22, scale = 0)) })
	public PrjOpnCritMappingId getId() {
		return this.id;
	}

	public void setId(PrjOpnCritMappingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRJ_SRVC_MAPPING_ID", nullable = false, insertable = false, updatable = false)
	public ProjectServiceMapping getProjectServiceMapping() {
		return this.projectServiceMapping;
	}

	public void setProjectServiceMapping(ProjectServiceMapping projectServiceMapping) {
		this.projectServiceMapping = projectServiceMapping;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "OPERATION_ID", referencedColumnName = "ID", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "SERVICE_ID", referencedColumnName = "SERVICE_ID", nullable = false, insertable = false, updatable = false) })
	public ServiceOperation getServiceOperation() {
		return this.serviceOperation;
	}

	public void setServiceOperation(ServiceOperation serviceOperation) {
		this.serviceOperation = serviceOperation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPLEXITY_DEFN_CODE", nullable = false)
	public RefCriteriaCustomDefn getRefCriteriaCustomDefn() {
		return this.refCriteriaCustomDefn;
	}

	public void setRefCriteriaCustomDefn(RefCriteriaCustomDefn refCriteriaCustomDefn) {
		this.refCriteriaCustomDefn = refCriteriaCustomDefn;
	}

	@Column(name = "CRITERIA_VALUE", precision = 22, scale = 0)
	public BigDecimal getCriteriaValue() {
		return this.criteriaValue;
	}

	public void setCriteriaValue(BigDecimal criteriaValue) {
		this.criteriaValue = criteriaValue;
	}

}
