package au.rms.nsw.gov.au.model.hibernate;
// Generated 14/10/2016 12:10:24 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProjectServiceMapping generated by hbm2java
 */
@Entity
@Table(name = "PROJECT_SERVICE_MAPPING", schema = "ESTADM")
public class ProjectServiceMapping implements java.io.Serializable {

	private BigDecimal prjSrvcMappingId;
	private Project project;
	private RefState refState;
	private Services services;
	private Set prjOpnCritMappings = new HashSet(0);
	private Set operationComplexities = new HashSet(0);

	public ProjectServiceMapping() {
	}

	public ProjectServiceMapping(BigDecimal prjSrvcMappingId, Project project, Services services) {
		this.prjSrvcMappingId = prjSrvcMappingId;
		this.project = project;
		this.services = services;
	}

	public ProjectServiceMapping(BigDecimal prjSrvcMappingId, Project project, RefState refState, Services services,
			Set prjOpnCritMappings, Set operationComplexities) {
		this.prjSrvcMappingId = prjSrvcMappingId;
		this.project = project;
		this.refState = refState;
		this.services = services;
		this.prjOpnCritMappings = prjOpnCritMappings;
		this.operationComplexities = operationComplexities;
	}

	@Id

	@Column(name = "PRJ_SRVC_MAPPING_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getPrjSrvcMappingId() {
		return this.prjSrvcMappingId;
	}

	public void setPrjSrvcMappingId(BigDecimal prjSrvcMappingId) {
		this.prjSrvcMappingId = prjSrvcMappingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATE_CODE")
	public RefState getRefState() {
		return this.refState;
	}

	public void setRefState(RefState refState) {
		this.refState = refState;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVICE_ID", nullable = false)
	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectServiceMapping")
	public Set getPrjOpnCritMappings() {
		return this.prjOpnCritMappings;
	}

	public void setPrjOpnCritMappings(Set prjOpnCritMappings) {
		this.prjOpnCritMappings = prjOpnCritMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectServiceMapping")
	public Set getOperationComplexities() {
		return this.operationComplexities;
	}

	public void setOperationComplexities(Set operationComplexities) {
		this.operationComplexities = operationComplexities;
	}

}
