package au.rms.nsw.gov.au.model.hibernate;
// Generated 14/10/2016 12:10:24 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefArchitectureLayer generated by hbm2java
 */
@Entity
@Table(name = "REF_ARCHITECTURE_LAYER", schema = "ESTADM")
public class RefArchitectureLayer implements java.io.Serializable {

	private String code;
	private String description;
	private Date inactiveDate;
	private ArchitectureCritMapping architectureCritMapping;
	private Set serviceses = new HashSet(0);

	public RefArchitectureLayer() {
	}

	public RefArchitectureLayer(String code, String description) {
		this.code = code;
		this.description = description;
	}

	public RefArchitectureLayer(String code, String description, Date inactiveDate,
			ArchitectureCritMapping architectureCritMapping, Set serviceses) {
		this.code = code;
		this.description = description;
		this.inactiveDate = inactiveDate;
		this.architectureCritMapping = architectureCritMapping;
		this.serviceses = serviceses;
	}

	@Id

	@Column(name = "CODE", unique = true, nullable = false, length = 4)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 15)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INACTIVE_DATE", length = 7)
	public Date getInactiveDate() {
		return this.inactiveDate;
	}

	public void setInactiveDate(Date inactiveDate) {
		this.inactiveDate = inactiveDate;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "refArchitectureLayer")
	public ArchitectureCritMapping getArchitectureCritMapping() {
		return this.architectureCritMapping;
	}

	public void setArchitectureCritMapping(ArchitectureCritMapping architectureCritMapping) {
		this.architectureCritMapping = architectureCritMapping;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refArchitectureLayer")
	public Set getServiceses() {
		return this.serviceses;
	}

	public void setServiceses(Set serviceses) {
		this.serviceses = serviceses;
	}

}
