package au.rms.nsw.gov.au.model.hibernate;
// Generated 14/10/2016 12:10:24 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefCriteria generated by hbm2java
 */
@Entity
@Table(name = "REF_CRITERIA", schema = "ESTADM")
public class RefCriteria implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private Set architectureCritMappings = new HashSet(0);
	private Set critCmplxityMsrs = new HashSet(0);

	public RefCriteria() {
	}

	public RefCriteria(BigDecimal id, String name) {
		this.id = id;
		this.name = name;
	}

	public RefCriteria(BigDecimal id, String name, Set architectureCritMappings, Set critCmplxityMsrs) {
		this.id = id;
		this.name = name;
		this.architectureCritMappings = architectureCritMappings;
		this.critCmplxityMsrs = critCmplxityMsrs;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refCriteria")
	public Set getArchitectureCritMappings() {
		return this.architectureCritMappings;
	}

	public void setArchitectureCritMappings(Set architectureCritMappings) {
		this.architectureCritMappings = architectureCritMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refCriteria")
	public Set getCritCmplxityMsrs() {
		return this.critCmplxityMsrs;
	}

	public void setCritCmplxityMsrs(Set critCmplxityMsrs) {
		this.critCmplxityMsrs = critCmplxityMsrs;
	}

}
