package au.rms.nsw.gov.au.model.hibernate;
// Generated 14/10/2016 12:10:24 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefComplexity generated by hbm2java
 */
@Entity
@Table(name = "REF_COMPLEXITY", schema = "ESTADM")
public class RefComplexity implements java.io.Serializable {

	private String code;
	private String description;
	private Set operationComplexities = new HashSet(0);
	private Set critCmplxityMsrsForCmplxityDefn = new HashSet(0);
	private Set critCmplxityMsrsForComplexityCode = new HashSet(0);

	public RefComplexity() {
	}

	public RefComplexity(String code, String description) {
		this.code = code;
		this.description = description;
	}

	public RefComplexity(String code, String description, Set operationComplexities,
			Set critCmplxityMsrsForCmplxityDefn, Set critCmplxityMsrsForComplexityCode) {
		this.code = code;
		this.description = description;
		this.operationComplexities = operationComplexities;
		this.critCmplxityMsrsForCmplxityDefn = critCmplxityMsrsForCmplxityDefn;
		this.critCmplxityMsrsForComplexityCode = critCmplxityMsrsForComplexityCode;
	}

	@Id

	@Column(name = "CODE", unique = true, nullable = false, length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refComplexity")
	public Set getOperationComplexities() {
		return this.operationComplexities;
	}

	public void setOperationComplexities(Set operationComplexities) {
		this.operationComplexities = operationComplexities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refComplexityByCmplxityDefn")
	public Set getCritCmplxityMsrsForCmplxityDefn() {
		return this.critCmplxityMsrsForCmplxityDefn;
	}

	public void setCritCmplxityMsrsForCmplxityDefn(Set critCmplxityMsrsForCmplxityDefn) {
		this.critCmplxityMsrsForCmplxityDefn = critCmplxityMsrsForCmplxityDefn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refComplexityByComplexityCode")
	public Set getCritCmplxityMsrsForComplexityCode() {
		return this.critCmplxityMsrsForComplexityCode;
	}

	public void setCritCmplxityMsrsForComplexityCode(Set critCmplxityMsrsForComplexityCode) {
		this.critCmplxityMsrsForComplexityCode = critCmplxityMsrsForComplexityCode;
	}

}
