package au.rms.nsw.gov.au.model.hibernate;
// Generated 14/10/2016 12:10:24 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefCriteriaCustomDefn generated by hbm2java
 */
@Entity
@Table(name = "REF_CRITERIA_CUSTOM_DEFN", schema = "ESTADM")
public class RefCriteriaCustomDefn implements java.io.Serializable {

	private String customDefnCode;
	private String description;
	private Set prjOpnCritMappings = new HashSet(0);

	public RefCriteriaCustomDefn() {
	}

	public RefCriteriaCustomDefn(String customDefnCode, String description) {
		this.customDefnCode = customDefnCode;
		this.description = description;
	}

	public RefCriteriaCustomDefn(String customDefnCode, String description, Set prjOpnCritMappings) {
		this.customDefnCode = customDefnCode;
		this.description = description;
		this.prjOpnCritMappings = prjOpnCritMappings;
	}

	@Id

	@Column(name = "CUSTOM_DEFN_CODE", unique = true, nullable = false, length = 15)
	public String getCustomDefnCode() {
		return this.customDefnCode;
	}

	public void setCustomDefnCode(String customDefnCode) {
		this.customDefnCode = customDefnCode;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refCriteriaCustomDefn")
	public Set getPrjOpnCritMappings() {
		return this.prjOpnCritMappings;
	}

	public void setPrjOpnCritMappings(Set prjOpnCritMappings) {
		this.prjOpnCritMappings = prjOpnCritMappings;
	}

}
