package au.rms.nsw.gov.au.model.hibernate;
// Generated 14/10/2016 12:10:24 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefState generated by hbm2java
 */
@Entity
@Table(name = "REF_STATE", schema = "ESTADM")
public class RefState implements java.io.Serializable {

	private String code;
	private String description;
	private Set projectServiceMappings = new HashSet(0);

	public RefState() {
	}

	public RefState(String code, String description) {
		this.code = code;
		this.description = description;
	}

	public RefState(String code, String description, Set projectServiceMappings) {
		this.code = code;
		this.description = description;
		this.projectServiceMappings = projectServiceMappings;
	}

	@Id

	@Column(name = "CODE", unique = true, nullable = false, length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 20)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refState")
	public Set getProjectServiceMappings() {
		return this.projectServiceMappings;
	}

	public void setProjectServiceMappings(Set projectServiceMappings) {
		this.projectServiceMappings = projectServiceMappings;
	}

}
