package au.rms.nsw.gov.au.model.hibernate;
// Generated 14/10/2016 12:10:24 PM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Services generated by hbm2java
 */
@Entity
@Table(name = "SERVICES", schema = "ESTADM")
public class Services implements java.io.Serializable {

	private BigDecimal id;
	private RefArchitectureLayer refArchitectureLayer;
	private String name;
	private String wsProtocol;
	private Set projectServiceMappings = new HashSet(0);
	private Set serviceOperations = new HashSet(0);

	public Services() {
	}

	public Services(BigDecimal id, RefArchitectureLayer refArchitectureLayer, String name) {
		this.id = id;
		this.refArchitectureLayer = refArchitectureLayer;
		this.name = name;
	}

	public Services(BigDecimal id, RefArchitectureLayer refArchitectureLayer, String name, String wsProtocol,
			Set projectServiceMappings, Set serviceOperations) {
		this.id = id;
		this.refArchitectureLayer = refArchitectureLayer;
		this.name = name;
		this.wsProtocol = wsProtocol;
		this.projectServiceMappings = projectServiceMappings;
		this.serviceOperations = serviceOperations;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ARCHITECTURE_LAYR_CODE", nullable = false)
	public RefArchitectureLayer getRefArchitectureLayer() {
		return this.refArchitectureLayer;
	}

	public void setRefArchitectureLayer(RefArchitectureLayer refArchitectureLayer) {
		this.refArchitectureLayer = refArchitectureLayer;
	}

	@Column(name = "NAME", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "WS_PROTOCOL", length = 10)
	public String getWsProtocol() {
		return this.wsProtocol;
	}

	public void setWsProtocol(String wsProtocol) {
		this.wsProtocol = wsProtocol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "services")
	public Set getProjectServiceMappings() {
		return this.projectServiceMappings;
	}

	public void setProjectServiceMappings(Set projectServiceMappings) {
		this.projectServiceMappings = projectServiceMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "services")
	public Set getServiceOperations() {
		return this.serviceOperations;
	}

	public void setServiceOperations(Set serviceOperations) {
		this.serviceOperations = serviceOperations;
	}

}
