package au.rms.nsw.gov.au.model.hibernate;
// Generated 14/10/2016 12:10:24 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ServiceOperation generated by hbm2java
 */
@Entity
@Table(name = "SERVICE_OPERATION", schema = "ESTADM")
public class ServiceOperation implements java.io.Serializable {

	private ServiceOperationId id;
	private Project project;
	private Services services;
	private String name;
	private Set operationComplexities = new HashSet(0);
	private Set prjOpnCritMappings = new HashSet(0);

	public ServiceOperation() {
	}

	public ServiceOperation(ServiceOperationId id, Services services, String name) {
		this.id = id;
		this.services = services;
		this.name = name;
	}

	public ServiceOperation(ServiceOperationId id, Project project, Services services, String name,
			Set operationComplexities, Set prjOpnCritMappings) {
		this.id = id;
		this.project = project;
		this.services = services;
		this.name = name;
		this.operationComplexities = operationComplexities;
		this.prjOpnCritMappings = prjOpnCritMappings;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "serviceId", column = @Column(name = "SERVICE_ID", nullable = false, precision = 22, scale = 0)) })
	public ServiceOperationId getId() {
		return this.id;
	}

	public void setId(ServiceOperationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVICE_ID", nullable = false, insertable = false, updatable = false)
	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceOperation")
	public Set getOperationComplexities() {
		return this.operationComplexities;
	}

	public void setOperationComplexities(Set operationComplexities) {
		this.operationComplexities = operationComplexities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceOperation")
	public Set getPrjOpnCritMappings() {
		return this.prjOpnCritMappings;
	}

	public void setPrjOpnCritMappings(Set prjOpnCritMappings) {
		this.prjOpnCritMappings = prjOpnCritMappings;
	}

}
